version: '3.8'

services:
  db:
    build: .
    container_name: cookbook-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cookbook

volumes:
  pgdata:
